version: "3"
services:
  home-assistant:
    image: homeassistant/home-assistant
    container_name: home-assistant
    environment:
      TZ: Europe/Oslo
    network_mode: host
    volumes:
      - ./config:/config
      - ./custom_components:/config/custom_components